### PR TITLE
Inserting dummy data

### PR DESCRIPTION
**Pull request by jtlin91**
@foodie-hackers/foodies Please review my dummy.js file which should insert all dummy data into my db. Thanks!

### CODE REVIEW

**Comment by Allantzhao** [comment]
Now that the data is in your database, maybe consider removing the functions or commenting out the functions that insert data. Everything else looks good!

**Comment by Allantzhao** [comment]
Also in line 3 in schema.sql what is the GO for?

**Comment by jtlin91** [comment]
yea my schema.sql wouldn't work right until i added the go.. weird right hahahah tbh i'm not 100% on why it has to be there.

as for the functions, that insert the data my thought process was that if we were to clone the app onto a diff machine it should stlil exist.  I don't mind commenting it out as long it's still there.  On the other hand, i was thinking it would be ok to leave it there because it's of no consequence since there is no script that runs 'dummy.js'  What do you think?

**Comment by Allantzhao** [comment]
Ohhh interesting. Then definitely keep it there!

I think you can leave the functions in if that's the case. I wasn't sure if you were running the file everytime or if it was only run once.

I also noticed that you are connecting to your database twice. Once in your index.js and the other through dummy.js. You might have to close the connection on dummy.js after the data is inserted to avoid conflicts with the other connection

**Comment by jtlin91** [comment]
Discussed and fix thru slack chat :]

**Pull request merged**
