### PR TITLE
Add css for main carousel

### PR DESCRIPTION
**Pull request by jtlin91**
@foodie-hackers/foodies 
Please check out my css for the main carousel!
Here's a scrnshot if you wish https://puu.sh/B5jY7/4be6111799.png

### CODE REVIEW

**Comment by chloewlin** [comment]
Hey @jtlin91! Your PR looks good to me. I'd set the background color of the caption to transparent so that its not completely black. You can do this in your next PR though.

**Comment by Allantzhao** [comment]
Hey @jtlin91! Like Chloe said your PR is looking good. 

One thing I think you can add in css is the light gray background on the page behind the carousel.

-Allan

**Comment by jtlin91** [comment]
@foodie-hackers/foodies 
Hey guys i have now completed css for my modal carousel.  I realize the info panel looks a bit empty aside from the caption but I figured I should work on some tests first.  I can render more stuff there later if time allows

**Comment by jtlin91** [comment]
Updated with a few more small style changes
Using static images as placeholders in info box

**Comment by Allantzhao** [comment]
@jtlin91 Everything looks good to me!

**Pull request merged**
